flaskProyectMVC/models/albumModel.py
from app import mysql

#METODO PARA OBTENER ALBUMS ACTIVOS
def getAll():
    cursor= mysql.connection.cursor()
    cursor.execute('SELECT * FROM tb_albums WHERE estatus = 1')
    consultaTodo = cursor.fetchall()
    cursor.close()
    return consultaTodo

#METODO PARA OBTENER LOS ALBUMS ELIMINADOS
def getAllDel():
    cursor = mysql.connection.cursor()
    cursor.execute('SELECT * FROM tb_albums WHERE estatus = 0')
    eliminados = cursor.fetchall()
    cursor.close()
    return eliminados

#METODO PARA OBTENER ALBUM POR ID
def getById(id):
    cursor= mysql.connection.cursor()
    cursor.execute('SELECT * FROM tb_albums WHERE id=%s',(id,))
    consultaId=cursor.fetchone()
    cursor.close()
    return consultaId

#METODO PRA INSERTAR UN ALBUM
def insertAlbum(titulo, artista, anio):
    cursor= mysql.connection.cursor()
    cursor.execute('insert into tb_albums(albums,artista,anio) values(%s,%s,%s)',(titulo,artista,anio))
    mysql.connection.commit()
    cursor.close()
    
#METODO PARA ACTUALIZAR UN ALBUM
def updateAlbum(Uid, Utitulo, Uartista, Uanio):
    cursor= mysql.connection.cursor()
    cursor.execute('UPDATE tb_albums SET albums = %s,artista = %s,anio = %s WHERE id = %s',(Utitulo, Uartista, Uanio, Uid))
    mysql.connection.commit()
    cursor.close()
    
#METODO PARA ELIMINAR ALBUM
def softDeleteAlbum(id):
    cursor = mysql.connection.cursor()
    cursor.execute('UPDATE tb_albums SET estatus = 0 WHERE id = %s', (id,))
    mysql.connection.commit()
    cursor.close()

flaskProyectMVC/app.py
from flask import Flask ,jsonify,render_template,request, url_for,flash,redirect
from flask_mysqldb import MySQL
import MySQLdb
from config import Config

app= Flask(__name__)
mysql=MySQL(app)

def create_app():
    app= Flask(__name__)
    app.config.from_object(Config)
    mysql.init_app(app)
    
    from controllers.albumController import albumsBP
    app.register_blueprint(albumsBP)
    
    return app

if __name__ == '__main__':
    app= create_app()
    app.run(port=3000,debug=True)

flaskProyectMVC/controllers/Controller.py
from flask import Blueprint, jsonify
from app import mysql
import MySQLdb

from config import Config

internoBP= Blueprint('inter', __name__)

#RUTAS DE GESTION INTERMNA 

# ruta para probar la conexion con mysql
@internoBP.route('/DBCheck')
def DB_ckeck():
    try:
        cursor= mysql.connection.cursor()
        cursor.execute('Select 1')
        return jsonify({'status':'ok','message':'Conectado con exito'}),200
    except MySQLdb.MySQLError as e:
        return jsonify({'status':'error','message':str(e)}),500


#ruta try-catch
#esta rura maneja los errores
@internoBP.errorhandler(404)
def paginaNoE(e):
    return 'Cuidado: Error de capa 8!'

#esta ruta maneja el error 405
@internoBP.errorhandler(405)
def metodonoP(e):
    return 'revisa el metodo de envio de tu ruta (GET o POST) !',405

flaskProyectMVC/controllers/albumController.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.albumModel import *

albumsBP= Blueprint('albums',__name__)

#RUTA DE INICIO DESDE EL APP
@albumsBP.route('/')
def home():
        try:
            consultaTodo = getAll()
            
            return render_template('formulario.html', errores={}, albums=consultaTodo)
        
        except Exception as e:

            flash('Algo fallo: '+ str(e))
            return render_template('formulario.html', errores={}, albums=[])

#RUTA PARA VER LOS ELIMINADOS
@albumsBP.route('/eliminados')
def eliminados():
    try:
        eliminados = getAllDel()
        
        return render_template('eliminados.html', albums=eliminados)
    except Exception as e:
        flash('Error al consultar eliminados: ' + str(e))
        return redirect(url_for('albums.home'))
        
#RUTA DE LA CONSULTA
@albumsBP.route('/consulta')
def consulta():
    return render_template('consulta.html', albums=[])
        

#RUTA DE CONSULTAR ID
@albumsBP.route('/detalles/<int:id>')
def detalle(id):
    try:
        consultaId = getById(id)
        
        return render_template('consulta.html', album=consultaId)
    
    except Exception as e:
        print('Error al consultar id: '+str(e))
        return redirect(url_for('albums.home'))


        
#RUTA DE GUARDAR
@albumsBP.route('/guardarAlbum',methods=['POST'])
def guardar():
    
    #listas de errores
    errores={}
    
    #obtener los datos a insertar
    #inputs de la vista
    titulo= request.form.get('txtTitulo','').strip()
    artista= request.form.get('txtArtista','').strip()
    anio= request.form.get('txtAnio','').strip()
    
    
    if not titulo:
        errores['txtTitulo']='Nombre del album OBLIGATORIO'
    if not artista:
        errores['txtArtista']='Nombre del artista OBLIGATORIO'
    if not anio:
        errores['txtAnio']='Año es OBLIGATORIO'
    elif not anio.isdigit() or int(anio)< 1800 or int(anio)> 2100:
        errores['txtAnio']='Ingresa un año valido'
        
    
    if not errores:
    #intentamos ejecutar el insert
        try:
            insertAlbum(titulo, artista, anio)
            
            flash('El album se guardo en la BD')
            return redirect(url_for('albums.home'))
        
        except Exception as e:
            mysql.connection.rollback()
            flash('Algo fallo: '+ str(e))
            return redirect(url_for('albums.home'))
    
    return render_template('formulario.html',errores=errores)
#return render_template('consulta.html')


#RUTA PARA EDITAR(ABRE EL FORM)
@albumsBP.route('/fromUpdate/<int:id>')
def fromUpdate(id):
    try:
        consultarId = getById(id)
        
        return render_template('fromUpdate.html', album=consultarId)
    
    except Exception as e:
        print('Error al actualizar id: '+str(e))
        return redirect(url_for('albums.consulta'))


#RUTA PARA EJECUTAR LA ACTUALIZACIÓN
@albumsBP.route('/actualizarAlbum',methods=['POST'])
def actualizar():
    
    #listas de errores
    errores={}

    #obtener los datos para actualizar
    #inputs de la vista
    Utitulo= request.form.get('txtTitulo','').strip()
    Uartista= request.form.get('txtArtista','').strip()
    Uanio= request.form.get('txtAnio','').strip()
    Uid= request.form.get('txtId')
    
    
    if not Utitulo:
        errores['txtTitulo']='Nombre del album OBLIGATORIO'
    if not Uartista:
        errores['txtArtista']='Nombre del artista OBLIGATORIO'
    if not Uanio:
        errores['txtAnio']='Año es OBLIGATORIO'
    elif not Uanio.isdigit() or int(Uanio)< 1800 or int(Uanio)> 2100:
        errores['txtAnio']='Ingresa un año valido'
        
    
    if not errores:
    #intentamos ejecutar el insert
        try:
            updateAlbum(Uid, Utitulo, Uartista, Uanio)
            
            flash('El album se actualizo en la BD')
            return redirect(url_for('albums.home'))
        
        except Exception as e:
            mysql.connection.rollback()
            flash('Algo fallo: '+ str(e))
            return redirect(url_for('albums.home'))

    
    if errores:
        album = (Uid, Utitulo, Uartista, Uanio)  # recreamos la tupla que espera la plantilla
        return render_template('fromUpdate.html', errores=errores, album=album)
    
    
#RUTA DEL SOFT DELETE
@albumsBP.route('/confirmDelete/<int:id>')
def confirmDelete(id):
    try:
        consultaId = getById(id)
        
        return render_template('confirmDel.html', album=consultaId)
    except Exception as e:
        flash('Error al obtener el álbum: ' + str(e))
        
        return redirect(url_for('albums.home'))


#RUTA DE CONFIRM DELETE    
@albumsBP.route('/eliminarAlbum/<int:id>', methods=['POST'])
def eliminarAlbum(id):
    id = request.form.get('id')

    try:
        softDeleteAlbum(id)
        
        flash('Álbum fue eliminado correctamente')
        return redirect(url_for('albums.home'))
    except Exception as e:
        mysql.connection.rollback()
        flash('Hubo un error al eliminar el álbum: ' + str(e))
        return redirect(url_for('albums.home'))


#RUTA DE

flaskProyectMVC/templates/confirmDel.html
{%extends 'plantilla.html'%}

    {%block body%}

    <div class="col-md-7"> <!--columna de 7 espacios -->    
    <h2 style="color: red;" class="display-4 text-primary mt-5 mb-5">¿Quieres eliminar el album?</h2>


    {% with mensajes = get_flashed_messages() %}
        {% if mensajes %}
            {% for msj in mensajes %}
                <h4 style="color: blue;">{{ msj }}</h4>
            {% endfor %}
        {% endif %}
    {% endwith %}

    <form action="{{ url_for('albums.eliminarAlbum', id=album[0]) }}" method="POST">

        <input type="hidden" name="id" value="{{ album[0] }}">

    <div class="col-md-7"> <!--columna de 7 espacios -->
    <table>
        <thead>
            <tr>
                <td> Album:</td>
                <td> Artista:</td>
                <td> Año de publicación:</td>
            </tr>
        </thead>


        <tbody>
            
            <tr>
                <td>{{ album[1] }}</td> 
                <td>{{ album[2] }}</td> 
                <td>{{ album[3] }}</td>

            </tr>
        </tbody>

    </table>
        <button type="submit" class="btn btn-success">Eliminar Álbum</button>
    </form>

    <br>
    <a href="{{ url_for('albums.home') }}">Regresar al Formulario</a>

    </div>
    </div>

    {%endblock%}

flaskProyectMVC/templates/consulta.html
{%extends 'plantilla.html'%}

    {%block body%}

<div class="row"> 

    <div class="col-md-5"><!--columna de 5 espacios -->
    
        <h2 class="display-4 text-primary mt-5 mb-5"> Vista de Consulta </h2>

    <table>
        <thead>
            <tr>
                    <td> ID:</td>
                    <td> Album:</td>
                    <td> Artista:</td>
                    <td> Año de publicación:</td>
            </tr>
        </thead>


        <tbody>
            
            <tr>
                <td>{{ album[0] }}</td>
                <td>{{ album[1] }}</td>
                <td>{{ album[2] }}</td>
                <td>{{ album[3] }}</td>
                
                <td><a href="{{ url_for('albums.fromUpdate', id=album[0])}}">Actualizar</a></td>
                <td><a href="{{ url_for('albums.confirmDelete', id=album[0])}}">Eliminar</a></td>
            </tr>
            
        </tbody>
    </table>


    <br>
    <a href="/"> Abrir vista del formulario </a>
</div>
</div>
    {%endblock%}

flaskProyectMVC/templates/formulario.html
{%extends 'plantilla.html'%}

    {%block body%}
<div class="row"> 
    
    <div class="col-md-5"><!--columna de 5 espacios -->
            <h2 class="display-4 text-primary mt-5 mb-5"> Vista del formulario </h2>
    <a href="/consulta"> Abrir vista de consulta </a>

        {% with mensajes= get_flashed_messages()%}
            {% if mensajes%}
                {% for msj in mensajes %}
                    <h4 style="color: blue;">{{ msj }}</h4>
                {% endfor%}
            {% endif%}
        {% endwith%}

    <form action="/guardarAlbum" method="post">

        <div class="mb-3">
        <input type="text" class="from-control" name="txtTitulo" placeholder="Titulo" value="{{ request.form.txtTitulo}}">

        {% if errores and errores.txtTitulo%}
                <p style="color:red">{{ errores.txtTitulo }}</p>
        {% endif%}
        </div>

        <div class="mb-3">
        <input type="text" class="from-control" name="txtArtista" placeholder="Artista" value="{{ request.form.txtArtista}}">

        {% if errores and errores.txtArtista%}
                <p style="color:red">{{ errores.txtArtista }}</p>
        {% endif%}
        </div>

        <div class="mb-3">
        <input type="number" class="from-control" name="txtAnio" placeholder="Año de publicación" value="{{ request.form.txtAnio}}">

        {% if errores and errores.txtAnio%}
                <p style="color:red">{{ errores.txtAnio }}</p>
        {% endif%}    
        </div>


        <div class="d-grid gap-2">
        <button type="submit" class="btn btn-success"> Guardar Album </button>
        </div>

    </form>
    </div> <!--columna de 5 espacios -->


    <div class="col-md-7"> <!--columna de 7 espacios -->
        <table>
        <thead>
            <tr>
                    <td> ID:</td>
                    <td> Album:</td>
            </tr>
        </thead>


        <tbody>

            {%for alb in albums%}
            <tr>
                <td>{{ alb.0}}</td>
                <td> <a href="/detalles/{{alb.0}}">{{ alb.1}}</a></td>
            </tr>
            {%endfor%}

        </tbody>
    </table>

    </div> <!--columna de 7 espacios -->

    
</div>

    {%endblock%}

flaskProyectMVC/templates/fromUpdate.html
{%extends 'plantilla.html'%}

    {%block body%}
<div class="row">
    <div class="col-md-5"><!--columna de 5 espacios -->
    <h2 class="display-4 text-primary mt-5 mb-5"> Vista de Actualizar </h2>

    {% with mensajes = get_flashed_messages() %}
        {% if mensajes %}
            {% for msj in mensajes %}
                <h4 style="color: blue;">{{ msj }}</h4>
            {% endfor %}
        {% endif %}
    {% endwith %}

    <form action="{{ url_for('albums.actualizar') }}" method="post">
       
        <input type="hidden" name="txtId" value="{{ album[0] }}">

    <div class="mb-3">
        <input type="text" name="txtTitulo" placeholder="Título" value="{{ request.form.txtTitulo if request.form.txtTitulo else album[1] }}">
        {% if errores and errores.txtTitulo %}
            <p style="color:red">{{ errores.txtTitulo }}</p>
        {% endif %}
    </div>
    
    <div class="mb-3">
        <input type="text" name="txtArtista" placeholder="Artista" value="{{ request.form.txtArtista if request.form.txtArtista else album[2] }}">
        {% if errores and errores.txtArtista %}
            <p style="color:red">{{ errores.txtArtista }}</p>
        {% endif %}
    </div>
    
    <div class="mb-3">
        <input type="number" name="txtAnio" placeholder="Año de publicación" value="{{ request.form.txtAnio if request.form.txtAnio else album[3] }}">
        {% if errores and errores.txtAnio %}
            <p style="color:red">{{ errores.txtAnio }}</p>
        {% endif %}
    </div>    

        <div class="d-grid gap-2">
        <button type="submit" class="btn btn-success">Actualizar Álbum</button>
        </div>

    </form>
    </div>
</div>

{%endblock%}

flaskProyectMVC/templates/plantilla.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">

    <title>Plantilla</title>
</head>

<body>

    {%block body%}

    {%endblock%}
    
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
</body>

</html>